# Generated by Django 5.2.1 on 2025-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_eventphoto_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
