# Generated by Django 5.2 on 2025-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
