# Generated by Django 5.2 on 2025-05-02 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_knowledgearticle_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgecomment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
