# Generated by Django 5.2 on 2025-05-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_text_knowledgecomment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
