# Generated by Django 5.2 on 2025-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_knowledgearticle_dislikes_knowledgearticle_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecomment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgecomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
