# Generated by Django 5.2 on 2025-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_knowledgecomment_dislikes_knowledgecomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='article_files/'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
