# Generated by Django 5.2 on 2025-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_knowledgearticle_attachment_knowledgearticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news_files/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
