# Generated by Django 5.2 on 2025-05-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_news_attachment_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
    ]
