# Generated by Django 5.2 on 2025-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalbum',
            name='event_date',
            field=models.DateField(verbose_name='Дата мероприятия'),
        ),
    ]
