# Generated by Django 5.2 on 2025-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_eventalbum_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalbum',
            name='event_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата мероприятия'),
        ),
    ]
