# Generated by Django 5.2 on 2025-05-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_eventcomment_dislikes_eventcomment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
