# Generated by Django 5.2.1 on 2025-05-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('news_app', '0003_alter_newscomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_app_news', to='app.newscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
